---
image: fedora/latest
packages:
  - python-pip
  - python3-pytest
  - python3-build
  - black
sources:
  - "https://git.sr.ht/~gary-kim/gkjh"
tasks:
  - install: |
      pip install -e gkjh
  - tests: |
      cd gkjh && pytest
  - style: |
      cd gkjh && black --check gkjh/ tests/
  - build: |
      cd gkjh && python3 -m build

